/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OverBoulderRouteImport } from './routes/over-boulder'
import { Route as BrancheEngineeringRouteImport } from './routes/branche/engineering'
import { Route as BrancheFinanceRouteImport } from './routes/branche/finance'
import { Route as VacatureSlugRouteImport } from './routes/vacature/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OverBoulderRoute = OverBoulderRouteImport.update({
  id: '/over-boulder',
  path: '/over-boulder',
  getParentRoute: () => rootRouteImport,
} as any)
const BrancheEngineeringRoute = BrancheEngineeringRouteImport.update({
  id: '/branche/engineering',
  path: '/branche/engineering',
  getParentRoute: () => rootRouteImport,
} as any)
const BrancheFinanceRoute = BrancheFinanceRouteImport.update({
  id: '/branche/finance',
  path: '/branche/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const VacatureSlugRoute = VacatureSlugRouteImport.update({
  id: '/vacature/$slug',
  path: '/vacature/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/over-boulder': typeof OverBoulderRoute
  '/branche/engineering': typeof BrancheEngineeringRoute
  '/branche/finance': typeof BrancheFinanceRoute
  '/vacature/$slug': typeof VacatureSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/over-boulder': typeof OverBoulderRoute
  '/branche/engineering': typeof BrancheEngineeringRoute
  '/branche/finance': typeof BrancheFinanceRoute
  '/vacature/$slug': typeof VacatureSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/over-boulder': typeof OverBoulderRoute
  '/branche/engineering': typeof BrancheEngineeringRoute
  '/branche/finance': typeof BrancheFinanceRoute
  '/vacature/$slug': typeof VacatureSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/over-boulder'
    | '/branche/engineering'
    | '/branche/finance'
    | '/vacature/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/over-boulder'
    | '/branche/engineering'
    | '/branche/finance'
    | '/vacature/$slug'
  id:
    | '__root__'
    | '/'
    | '/over-boulder'
    | '/branche/engineering'
    | '/branche/finance'
    | '/vacature/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OverBoulderRoute: typeof OverBoulderRoute
  BrancheEngineeringRoute: typeof BrancheEngineeringRoute
  BrancheFinanceRoute: typeof BrancheFinanceRoute
  VacatureSlugRoute: typeof VacatureSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-boulder': {
      id: '/over-boulder'
      path: '/over-boulder'
      fullPath: '/over-boulder'
      preLoaderRoute: typeof OverBoulderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branche/engineering': {
      id: '/branche/engineering'
      path: '/branche/engineering'
      fullPath: '/branche/engineering'
      preLoaderRoute: typeof BrancheEngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branche/finance': {
      id: '/branche/finance'
      path: '/branche/finance'
      fullPath: '/branche/finance'
      preLoaderRoute: typeof BrancheFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacature/$slug': {
      id: '/vacature/$slug'
      path: '/vacature/$slug'
      fullPath: '/vacature/$slug'
      preLoaderRoute: typeof VacatureSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OverBoulderRoute: OverBoulderRoute,
  BrancheEngineeringRoute: BrancheEngineeringRoute,
  BrancheFinanceRoute: BrancheFinanceRoute,
  VacatureSlugRoute: VacatureSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
